name: Build and Publish DB Models

on:
  push:
    #branches: [ main ]
    #paths:
    #  - 'db/init/**'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mydb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      CONNECTION_STRING: "host=localhost user=postgres password=postgres dbname=mydb"


    defaults:
      run:
        working-directory: generator


    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v5

      - name: Restore tools
        run: dotnet tool restore

      - name: Install psql
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Apply SQL scripts
        run: |
          set -e

          echo "Applying SQL scripts from db/init..."
          
          FILES=$(find db/init -name "*.sql" | sort -V)

          for file in $FILES; do
            echo "Running $file"
            psql "$CONNECTION_STRING" -v ON_ERROR_STOP=1 -f "$file"
          done


      - name: Verify tables
        run: |
          psql "$CONNECTION_STRING" -c "\dt"

      - name: Scaffold EF Core models
        run: |
          dotnet ef dbcontext scaffold \
            "$CONNECTION_STRING" \
            Npgsql.EntityFrameworkCore.PostgreSQL \
            --project src/DfE.EducationProviderRegistry.Data.DatabaseModels \
            --output-dir Models \
            --context-dir Context \
            --context EducationProviderRegistryDbContext \
            --no-pluralize \
            --no-onconfiguring \
            --force

      - name: Detect changes
        id: diff
        run: |
          git diff --exit-code || echo "changed=true" >> $GITHUB_ENV

      - name: Set package version
        run: |
          VERSION=1.0.${{ github.run_number }}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: NuGet Package Database Models
        run: |
          dotnet pack src/DfE.EducationProviderRegistry.Data.DatabaseModels \
            -c Release \
            -o ./nupkg \
            /p:PackageVersion=${{ env.VERSION }}
        
      - name: Publish package
        if: env.changed == 'true'
        run: |
          dotnet nuget push "./nupkg/DfE.EducationProviderRegistry.Data.DatabaseModels.nupkg" \
            --api-key ${{ secrets.GITHUB_TOKEN }} \
            --source "https://nuget.pkg.github.com/Dfe-digital/index.json" \
            --skip-duplicate
